server:
  port: 8000

# 路由转发，将/member/...的请求转发了member模块
spring:
  cloud:
    gateway:
      routes:
        - id: member
          predicates:
            - Path=/member/** #所有的/member/**开头的请求都会被转发到下列uri
          uri: http://127.0.0.1:8001
          #uri: lb://member